In [1]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = a.T

In [2]:
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
import numpy as np 
a = np.ones(2)
b = np.ones((1,2))

In [4]:
a

array([1., 1.])

In [5]:
b

array([[1., 1.]])

In [6]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [7]:
import numpy as np 
a = np.array([[1, 0], [2, -1]])
r = a * a

In [8]:
r

array([[1, 0],
       [4, 1]])

In [9]:
import numpy as np

np.random.random((2,2))

array([[0.17151078, 0.8106686 ],
       [0.75065822, 0.66247392]])

In [10]:
import numpy as np
a = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
a[-1,-1] = 0
a[a.shape[0]-2, 1] = a[0, -1] + a[-1, 0]
a[0,0]= a[0,2] + a[2,0]

In [11]:
a

array([[10,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  0]])

In [13]:
import numpy as np
a = np.array([[1,2, 3], [4,5,6]]) 
b = a.reshape(-1)

In [14]:
b

array([1, 2, 3, 4, 5, 6])

In [15]:
import numpy as np
a = np.array([[1,2], [3,4]])
#A list comprehension 
b = [a[j,i] for i in range(a.shape[0]) for j in range(a.shape[1])]

In [16]:
b

[1, 3, 2, 4]

In [17]:
import numpy as np 

a = np.zeros((2,2))

b = np.eye(2)

In [18]:
a

array([[0., 0.],
       [0., 0.]])

In [19]:
b

array([[1., 0.],
       [0., 1.]])

In [20]:
import numpy as np 

b = np.mat([[5, 6], [7, 8]])

In [21]:
b

matrix([[5, 6],
        [7, 8]])

In [22]:
import numpy as np
a = np. array([ [1, 2], [3, 4] ])
print(round(np.var(a),2) == round(np.std(a)**2,2))

True


In [23]:
import numpy as np
a = np.array([1,2, 3, []]) 
a[-1].append(4)
a[-1].append(5)
print(len(a))

4


In [24]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [25]:
x

array([[1., 0.],
       [0., 0.]])

In [26]:
y

matrix([[1., 1.],
        [2., 0.]])

In [27]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a[0] = a[0,::-1]
a[:,1]=a[::-1,1]

In [28]:
a

array([[ 5,  7,  3,  2,  1],
       [ 6,  4,  8,  9, 10]])

In [29]:
import numpy as np 
a = np.zeros((2,2))
b = np.eye(2)

In [32]:
a
b

array([[1., 0.],
       [0., 1.]])

In [31]:
b

array([[1., 0.],
       [0., 1.]])

In [33]:
import numpy as np
a = np. array([ [1, 2], [3, 4] ]) 
print(np.mean(a, axis=None)== np.mean(a))

True


In [34]:
import numpy as np 
a = np.matrix([[1, 0], [2, -1]])
r = a * a

In [35]:
r

matrix([[1, 0],
        [0, 1]])

In [36]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [37]:
x

array([[1., 0.],
       [0., 0.]])

In [38]:
y

matrix([[1., 1.],
        [2., 0.]])

In [39]:
import numpy as np
a = np.array( [[1,2, 3, 4],  [5,6, 7, 8],  [9,10,11,12]] )
b = a[1:3, 2:]
b

array([[ 7,  8],
       [11, 12]])

In [40]:
import numpy as np 

a = np.array([[10, 11, 12]])
b = np.array([[20], [21], [22]])
c = np.array([[1,2], [3,4], [5,6]])
print(a.shape, b.shape, c.shape)

(1, 3) (3, 1) (3, 2)


In [41]:
import numpy as np
a = np.array([[1,2], [3,4]])
#A list comprehension 
b = [a[j,i] for i in range(a.shape[0]) for j in range(a.shape[1])]

In [42]:
b

[1, 3, 2, 4]

In [43]:
import numpy as np 
a = np.matrix([[1, 0], [2, -1]])
r = a * a

In [44]:
r

matrix([[1, 0],
        [0, 1]])

In [45]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [46]:
import numpy as np 

a = np.zeros((2,2))

b = np.eye(2)

In [47]:
a

array([[0., 0.],
       [0., 0.]])

In [48]:
b

array([[1., 0.],
       [0., 1.]])

In [49]:
import numpy as np
a = np. array([ [1, 2], [3, 4] ])
print(round(np.var(a),2) == round(np.std(a)**2,2))

True


In [50]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [51]:
x

array([[1., 0.],
       [0., 0.]])

In [52]:
y

matrix([[1., 1.],
        [2., 0.]])

In [53]:
x

array([[1., 0.],
       [0., 0.]])

In [54]:
y

matrix([[1., 1.],
        [2., 0.]])

In [55]:
import numpy as np 

a = np.array([[10, 11, 12]])
b = np.array([[20], [21], [22]])
c = np.array([[1,2], [3,4], [5,6]])
print(a.shape, b.shape, c.shape)

(1, 3) (3, 1) (3, 2)


In [59]:
import numpy as np 

b = np.mat([[5, 6], [7, 8]])
b

matrix([[5, 6],
        [7, 8]])

In [60]:
import numpy as np
a = np.array( [[1,2, 3, 4],  [5,6, 7, 8],  [9,10,11,12]] )
b = a[1:3, 2:]
b

array([[ 7,  8],
       [11, 12]])

In [61]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [62]:
x

array([[1., 0.],
       [0., 0.]])

In [63]:
y

matrix([[1., 1.],
        [2., 0.]])

In [64]:
import numpy as np 
a = np.ones(2)
b = np.ones((1,2))

In [65]:
a

array([1., 1.])

In [66]:
b

array([[1., 1.]])