# Olivia Storaci
## Week 12 - 04/07/2022
### Python NumPy Universal Functions

In [1]:
import numpy as np

arr=np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
# Square Root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
# Exponents
np.ep(arr)

AttributeError: module 'numpy' has no attribute 'ep'

In [4]:
# Randn
arr1 = np.random.randn(10) # Return a sample (or sample) from the 'standard normal' distribution
arr1

array([-0.95730507,  1.35835533, -0.85371049, -1.3706307 ,  1.11813845,
        0.14895928, -0.76132403, -1.73006945, -2.00040167,  1.20909403])

In [5]:
arr2 = np.random.randn(10)
arr2

array([ 0.73375693, -0.87384551,  0.38822458, -1.51341644,  1.32838021,
       -1.68550709,  1.04592848, -0.05171678, -0.37439733, -0.46580863])

In [6]:
# Add
np.add(arr1,arr2)

array([-0.22354814,  0.48450982, -0.46548591, -2.88404713,  2.44651866,
       -1.53654781,  0.28460446, -1.78178623, -2.374799  ,  0.7432854 ])

In [7]:
# Maximum
np.maximum(arr1,arr2)

array([ 0.73375693,  1.35835533,  0.38822458, -1.3706307 ,  1.32838021,
        0.14895928,  1.04592848, -0.05171678, -0.37439733,  1.20909403])

In [8]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr2=np.ones(9).reshape((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.add(arr1,arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [11]:
# Array Filtering
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
print(arr<4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [14]:
# Replace values of an array using where
# np.where(condition, x, y) return elements from 'x' or 'y' depending on condition
np.where(arr<4, True, False)

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [15]:
np.where(arr<4, -1, -2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [16]:
np.where((arr<4)&(arr>2), -1, -2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [17]:
# Where with 1-D
arr1 = np.array([1,2,3,4,5])
arr2 = arr1*10
arr_b = np.array([True,False,True,True,False])
print(arr1)
print(arr2)
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [18]:
# zip
zip(arr1,arr2,arr_b)

In [19]:
list(zip(arr1,arr2,arr_b))

[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]

In [20]:
# Using List Comprehension
arr3=[r1 if b else r2 for r1,r2,b in zip(arr1,arr2,arr_b)]
arr3

[1, 20, 3, 4, 50]

In [21]:
# Using np.where
arr3 = np.where(arr_b,arr1,arr2)
arr3

array([ 1, 20,  3,  4, 50])

In [23]:
# Using where with 2-D array
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,False]])

print("arr1: ", arr1, end="\n\n")
print("arr2: ", arr2, end="\n\n")
print("cond: ", cond,  end="\n\n")

arr1:  [[1 2]
 [3 4]]

arr2:  [[5 6]
 [7 8]]

cond:  [[ True False]
 [ True False]]



In [24]:
np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 8]])

In [25]:
np.where([[True,False],[True,False]], [[5,6],[7,8]], [[1,2],[3,4]])

array([[5, 2],
       [7, 4]])

In [26]:
# A short use of randn
from numpy.random import randn
arr = randn(3,3)
arr

array([[-2.31392326,  0.83816403, -1.76719481],
       [ 0.87705662,  0.6995935 ,  1.18382735],
       [ 1.54839953, -0.06216005,  0.55191535]])

In [27]:
np.where(arr<0,0,arr)

array([[0.        , 0.83816403, 0.        ],
       [0.87705662, 0.6995935 , 1.18382735],
       [1.54839953, 0.        , 0.55191535]])

In [28]:
# Boolean Arrays
# Any
arr_b = np.array([True,False,True,False,False])
arr_b.any() #Returns true if any elements if 'a' eveluate to true

True

In [29]:
# All
arr_b.all() # Returns true if all elements eveluate to true

False

In [30]:
# Unique()
# Find the unique elements of an array
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [31]:
# in 1d
np.in1d(['Apple','Cherry','Grape'], fruits)

array([ True,  True, False])