# Olivia Storaci
## Week 12 - 04/07/2022
### Python NumPy Universal Functions

In [1]:
import numpy as np

arr=np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
# Square Root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
# Exponents
np.ep(arr)

AttributeError: module 'numpy' has no attribute 'ep'

In [ ]:
# Randn
arr1 = np.random.randn(10) # Return a sample (or sample) from the 'standard normal' distribution
arr1

In [ ]:
arr2 = np.random.randn(10)
arr2

In [ ]:
# Add
np.add(arr1,arr2)

In [ ]:
# Maximum
np.maximum(arr1,arr2)

In [ ]:
arr1 = np.arange(9).reshape((3,3))
arr1

In [ ]:
arr2=np.ones(9).reshape((3,3))
arr2

In [ ]:
np.add(arr1,arr2)

In [ ]:
# Array Filtering
arr = np.arange(9).reshape(3,3)
arr

In [ ]:
print(arr<4)

In [ ]:
# Replace values of an array using where
# np.where(condition, x, y) return elements from 'x' or 'y' depending on condition
np.where(arr<4, True, False)

In [ ]:
np.where(arr<4, -1, -2)

In [ ]:
np.where((arr<4)&(arr>2), -1, -2)

In [ ]:
# Where with 1-D
arr1 = np.array([1,2,3,4,5])
arr2 = arr1*10
arr_b = np.array([True,False,True,True,False])
print(arr1)
print(arr2)
print(arr_b)

In [ ]:
# zip
zip(arr1,arr2,arr_b)

In [ ]:
list(zip(arr1,arr2,arr_b))

In [ ]:
# Using List Comprehension
arr3=[r1 if b else r2 for r1,r2,b in zip(arr1,arr2,arr_b)]
arr3

In [ ]:
# Using np.where
arr3 = np.where(arr_b,arr1,arr2)
arr3

In [ ]:
# Using where with 2-D array
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,False]])

print("arr1: ", arr1, end="\n\n")
print("arr2: ", arr2, end="\n\n")
print("cond: ", cond,  end="\n\n")

In [ ]:
np.where(cond,arr1,arr2)

In [ ]:
np.where([[True,False],[True,False]], [[5,6],[7,8]], [[1,2],[3,4]])

In [ ]:
# A short use of randn
from numpy.random import randn
arr = randn(3,3)
arr

In [ ]:
np.where(arr<0,0,arr)

In [ ]:
# Boolean Arrays
# Any
arr_b = np.array([True,False,True,False,False])
arr_b.any() #Returns true if any elements if 'a' eveluate to true

In [ ]:
# All
arr_b.all() # Returns true if all elements eveluate to true

In [ ]:
# Unique()
# Find the unique elements of an array
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])
np.unique(fruits)

In [ ]:
# in 1d
np.in1d(['Apple','Cherry','Grape'], fruits)

In [5]:
import numpy as np

In [6]:
# Descriptive Statistical Measures
# See that is is a 3,3 Dimension. Three rows and 3 columns. 
arr = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Adds all of them together one by one
arr.sum()

45

In [8]:
# 1,4,7 first column added together. 
arr.sum(0)

array([12, 15, 18])

In [9]:
arr.sum(1)

array([ 6, 15, 24])

In [10]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# Specify the axis = 0 and it gives you the same result as arr.sum(0)
np.sum(arr, axis=0)

array([12, 15, 18])

In [12]:
# Sum for the Rows
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [13]:
# Do not specify the axis and it gives you the sum of all numbers in array
np.sum(arr,axis=None)

45

In [14]:
# Mean()
arr.mean()

5.0

In [15]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr.mean(0)

array([4., 5., 6.])

In [18]:
# Mean for the Rows instead of the columns
arr.mean(1)

array([2., 5., 8.])

In [19]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [20]:
np.mean(arr,axis=None)

5.0

In [21]:
arr.var()

6.666666666666667

In [22]:
arr.std()

2.581988897471611

In [23]:
# Sort the elements in the array
arr = np.array([3,6,8,1,9,10,3,5,63,9,12,10,15,11,14])
arr.sort()

In [24]:
# Print the sorted array
arr

array([ 1,  3,  3,  5,  6,  8,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [25]:
arr

array([ 1,  3,  3,  5,  6,  8,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [28]:
# Transpose
arr = np.array([ [1,2,3,4],[5,6,7,8] ])
print(arr.shape)
print(arr)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [29]:
# Transpose columns to rows and rows to columns
t = arr.T
t

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
t.shape

(4, 2)

In [31]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [32]:
# Hows you that it is 4,2. 4 rows and 2 columns
arr.transpose().shape

(4, 2)

In [34]:
# Original Array. 
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [35]:
# Nothing has been changed. Axis 0 and 1 keep them as they are. Just t is flip the rows with the columns. 0,1 dont change anythiung 
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
# Flip the Axis 0 with axis 1. 
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [37]:
# NOW is 4 rows and 2 columns 
arr.shape

(2, 4)

In [38]:
arr.transpose((0,1)).shape

(2, 4)

In [39]:
arr.transpose((1,0)).shape

(4, 2)

In [40]:
# Using t is default changing rows and columns

In [42]:
# Universal function. 2 rows, 5 columns, 2 elements
arr_3d=np.arange(20).reshape((2,5,2))
print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [43]:
arr_3d.transpose((0,1,2)) # 0 a the begining is no change in the axis, same order

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [44]:
# Show me the shape of this transpose
arr_3d.transpose((0,1,2)).shape

(2, 5, 2)

In [46]:
# Flip 1 with 0. Now we hav 5 elements. each has two elements and two elements inside. 
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [47]:
# Send the shape and parameters as a tuple = more control than just using the .t
arr_3d.transpose((1,0,2)).shape

(5, 2, 2)

In [49]:
# Does not have any affect. Two elements
arr_3d.T

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [50]:
# Random numbers in an array that is 1d 4 by 4
np.random.random((4,4)) # Generates numbers within this interval [0.0, 1.0]

array([[0.53595591, 0.2308454 , 0.14942194, 0.96296012],
       [0.42489837, 0.27429657, 0.41798232, 0.66099507],
       [0.79878818, 0.77627888, 0.38849646, 0.9939637 ],
       [0.70838392, 0.86375622, 0.11764948, 0.89215051]])

In [51]:
# Import the function that allows you to generate random numbers 

from numpy.random import random

random((4,4))

array([[0.05457822, 0.06327211, 0.04782643, 0.57072557],
       [0.15503356, 0.28267993, 0.52138829, 0.85892337],
       [0.54998038, 0.92383693, 0.56759381, 0.90032405],
       [0.06328618, 0.55405001, 0.97216386, 0.08799386]])

In [53]:
from numpy.random import randn
randn(5,5)

array([[ 1.06067694,  0.77701666, -0.78369989,  0.04577249, -0.52062121],
       [-1.07694389, -0.00769859,  0.17932023, -0.1638498 ,  0.00308345],
       [-0.04556813, -0.63101781, -0.40885132,  1.16448328, -0.08557215],
       [ 1.69127824,  0.41911535, -0.63361345, -0.33436077,  0.7856933 ],
       [-0.81087776,  0.48370227, -1.01386328,  0.17413439,  1.22121607]])

In [55]:
# Random list of numbers
randn(5)

array([0.48854578, 0.67024147, 0.81875157, 0.17266471, 0.34493107])

In [58]:
# Random Integers
np.random.randint(10,50)

37

In [59]:
# Joining Numpy Arrays
# 1-d array

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1,"\n",arr2)

[1 2 3 4 5] 
 [ 6  7  8  9 10]


In [61]:
# Now do the Join via concatenation. Will go by axis. Shows that it is 1 level. Array of one dimension
arr = np.concatenate((arr1,arr2))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr.shape

(10,)

In [64]:
# Join a 2-d array. Print and seperate the arrays
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1,'\n\n',arr2)

[[1 2]
 [3 4]] 

 [[5 6]
 [7 8]]


In [65]:
# Complete the join. Now they are all one. Twice the size. But now one 2-d array
arr=np.concatenate((arr1,arr2))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
# Both are 2,2
arr1.shape

(2, 2)

In [67]:
arr2.shape

(2, 2)

In [68]:
# generated array 4,2
arr.shape

(4, 2)

In [70]:
# Concatenate based on the axis. 
arr = np.concatenate((arr1,arr2), axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [71]:
arr.shape

(2, 4)

In [72]:
arr = np.concatenate((arr1,arr2), axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
arr.shape

(4, 2)

In [74]:
# Splitting NumPy Arrays. Split the array into 3!! Generated a list of arrays
arr = np.array([1,2,3,4,5,6])
arr_s = np.array_split(arr,3)
arr_s

[array([1, 2]), array([3, 4]), array([5, 6])]

In [75]:
arr_s[0]

array([1, 2])

In [76]:
arr_s[2]

array([5, 6])

In [78]:
website = "https://docs.scipy.org/doc/numpy/reference/"
'''
There are currently more than 60 universal functions
'''
import webbrowser
webbrowser.Chrome

webbrowser.Chrome